#!/usr/bin/env python
import sys
import fcntl
import os

file_name = os.path.abspath(sys.argv[1])
x = open(file_name,"rb")
y = open("/tmp/upload_to_discord/"+file_name,"wb")
fcntl.lockf(y,fcntl.LOCK_EX)
y.write(x.read())

fcntl.lockf(y, fcntl.LOCK_UN)
x.close()
y.close()