#!/usr/bin/env python
#https://github.com/CodeRic28/Projects/blob/master/recursive_calc.py
#This function evaluates the expression inside parentheses
def brac(exp):
    while "(" in exp:
        c_brac = o_pos = exp.index(")")
        while exp[o_pos] != "(":
            o_pos -= 1
        o_brac = o_pos
        brac_exp = exp[o_brac+1 : c_brac]
        if '*-' in brac_exp or '/-' in brac_exp or '--' in exp or '+-' in exp:
            val = stmin(brac_exp)
            exp = exp[:o_brac] + str(val) + exp[c_brac + 1:]
        else:
            exp = exp[:o_brac] + str(evaluate(brac_exp)) + exp[c_brac + 1:]
    return evaluate(exp)

#This function identifies the number to the left of the operator
def lft(exp, pos):
    i = pos-1
    while exp[i].isnumeric() is True or exp[i] == '.':
        i=i-1
        if i<0:
            break
    return exp[i+1:pos]

#This function identifies the number to the right of the operator
def rgt(exp, pos):
    i = pos+1
    while exp[i].isnumeric() is True or exp[i] == '.':
        i=i+1
        if i >= len(exp):
            break
    return exp[pos+1:i]

#This function is used to identify is two operators are together. If there is a * and / followed by a - sign then move the '-' sign until it encounters a '+' or '-' sign.
#If it encounters a '-' sign, it changes it to '+' sign and vice-versa.
#If there is a ^ followed by a - then it changes the expression to 1/a^b form
def stmin(exp):
    if '*-' in exp:
        star_pos = exp.find('*-')
        min_pos = star_pos + 1
        left = exp[:min_pos]
        right = exp[min_pos+1:]
        i = star_pos - 1
        while exp[i].isnumeric() is True or exp[i] == '.' or exp[i] == '*' or exp[i] == '/':
            i=i-1
            if exp[i] == '+' or exp[i] == '-':
                break
            elif i<0: break
        sign = i
        if exp[sign] == '+':
            exp = exp[:sign] + str('-') + exp[sign+1:min_pos] + exp[min_pos+1:]
        elif exp[sign] == '-':
            exp = exp[:sign] + str('+') + exp[sign+1:min_pos] + exp[min_pos+1:]
            if exp[0] == '+':
                exp = exp[1:]
        else:
            exp = exp[min_pos] + left + right

    elif '/-' in exp:
        star_pos = exp.find('/-')
        min_pos = star_pos + 1
        left = exp[:min_pos]
        right = exp[min_pos + 1:]
        i = star_pos - 1
        while exp[i].isnumeric() is True or exp[i] == '.' or exp[i] == '*' or exp[i] == '/':
            i = i - 1
            if exp[i] == '+' or exp[i] == '-':
                break
            elif i < 0:
                break
        sign = i
        if exp[sign] == '+':
            exp = exp[:sign] + str('-') + exp[sign + 1:min_pos] + exp[min_pos + 1:]
        elif exp[sign] == '-':
            exp = exp[:sign] + str('+') + exp[sign + 1:min_pos] + exp[min_pos + 1:]
            if exp[0] == '+':
                exp = exp[1:]
        else:
            exp = exp[min_pos] + left + right            
    elif '^-' in exp:
        star_pos = exp.find('^-')
        min_pos = star_pos + 1
        left = exp[:min_pos]
        right = exp[min_pos+1:]
        l = lft(exp, star_pos)
        r = rgt(exp, star_pos)
        exp = exp[:star_pos-len(l)] + str('1/') + l + str('^') + r + exp[star_pos+len(r)+2:]

    elif '--' in exp:
        star_pos = exp.find('--')
        min_pos = star_pos + 1
        left = exp[:star_pos]
        right = exp[min_pos + 1:]
        exp = left + '+' + right

    elif '+-' in exp:
        star_pos = exp.find('+-')
        min_pos = star_pos + 1
        left = exp[:star_pos]
        right = exp[min_pos + 1:]
        exp = left + '-' + right
    return brac(exp)

#This function checks if there are two or more - sign in an expression
def check(exp, pos_op):
    minus = exp[pos_op]
    if '-' in exp[pos_op + 1:]:
        r = rgt(exp, pos_op)
        # print(r)
        f = r.find(r)
        l = exp[:pos_op+1]
        l = len(l)
        rpos = len(r)
        if exp[pos_op + rpos + 1] == '-':
            s = rgt(exp, pos_op + rpos + 1)
            exp = exp[:pos_op] + minus + '(' + r + '+' + s + ')' + exp[pos_op + rpos + len(s)+2:]
    return brac(exp)

#This is the function in which to expression actually executes
def evaluate(exp):
    if '*-' in exp or '/-' in exp or '^-' in exp or '--' in exp or '+-' in exp:
        exp = stmin(exp)
        if type(exp) is float:
            exp = str(exp)
    if "+" in exp:
        pos_op = exp.find("+")
        left = exp.split("+")[0]
        right = exp[pos_op+1:]
        return evaluate(left) + evaluate(right)
    elif "-" in exp:
        pos_op = exp.find("-")
        count = 0
        for x in exp:
            if x == '-':
                count+=1
        if count>=2:
            return float(check(exp, pos_op))
        else:
            left = exp.split("-")[0]
            if left == '':
                left = '0'
            right = exp[pos_op + 1:]
            return evaluate(left) - evaluate(right)

    elif "*" in exp:
        pos_op = exp.find("*")
        left = exp.split("*")[0]
        right = exp[pos_op + 1:]
        return evaluate(left) * evaluate(right)
    elif "/" in exp:
        pos_op = exp.find("/")
        left = exp.split("/")[0]
        right = exp[pos_op + 1:]
        return evaluate(left) / evaluate(right)
    elif "^" in exp:
        pos_op = exp.find("^")
        left = exp.split("^")[0]
        right = exp[pos_op + 1:]
        return evaluate(left) ** evaluate(right)
    else:
        return float(exp)

inp = input("Enter an expression: ")
if "(" in inp:
    print(brac(inp))
else:
    print(evaluate(inp))
